### PR TITLE
First) format and lint cairo-demo and cairo_shadow_button

### PR DESCRIPTION
**Pull request by theavege**

### CODE REVIEW

**Comment by theavege** [comment]
@MoAlyousef I think the new version is not built on MacOS

**Comment by MoAlyousef** [comment]
It seems to be this issue here:
https://github.com/fltk-rs/fltk-rs/issues/1536#event-12365462543

It should be fixed now in version 1.4.28

**Comment by theavege** [comment]
@MoAlyousef, Please accept the PR.

**Comment by theavege** [comment]
@MoAlyousef Can you accept this Pull Request?
Is any complaints about it?

**Pull request merged**
