### PR TITLE
add flhudson' live demo

### PR DESCRIPTION
**Pull request by theavege**
Terve!

@MoAlyousef I add FlHudson's live demo. It's a FLTK's shell for running some console programs (siege, virsh).
Can you add handling for deactivated widgets?

Kiitos, ystävällisin terveisin
Artöm

### CODE REVIEW

**Comment by MoAlyousef** [comment]
Hello @theavege 
What do you mean by "Can you add handling for deactivated widgets"?

**Comment by theavege** [comment]
If widget is deactivated, then it can handle some event.
For example: I want to activate and deactivate some widget through handle + event.

**Comment by MoAlyousef** [comment]
If you can provide a minimal reproducible example of what you're trying to do, that would be helpful.

**Comment by theavege** [comment]
```
use fltk::{
    app,
    button::Button,
    enums::{FrameType, Event},
    valuator::Dial,
    group::Flex,
    prelude::*,
    window::Window,
};

const HEARTBEAT: Event = Event::from_i32(404);

fn main() {
    let app = app::App::default().with_scheme(app::Scheme::Plastic);
    let mut wind = Window::default().with_size(640, 360).with_label("Dial");
    {
        let mut page = Flex::default().with_size(100, 200).center_of_parent().column();
        crate::dial();
        Button::default().with_label("@circle").set_callback(move |_| {
            app::handle_main(HEARTBEAT).unwrap();
        });
        page.end();
        page.set_frame(FrameType::FlatBox);
        page.set_margin(10);
        page.set_pad(10);
    }
    wind.end();
    wind.show();
    app.run().unwrap();
}

fn dial() {
    const DIAL: u8 = 120;
    let mut element = Dial::default();
    element.deactivate();
    element.set_maximum((DIAL / 4 * 3) as f64);
    element.set_value(element.minimum());
    element.handle(move |dial, event| if event == HEARTBEAT {
        dial.set_value(match dial.value() == (DIAL - 1) as f64 {
            true => dial.minimum(),
            false => dial.value() + 1f64,
        });
        true
    } else {
        false
    });
}
```

**Comment by theavege** [comment]
Why does this cause an error?

```
app::GlobalState::<HashMap<String, SharedImage>>::new(HashMap::new());
```

**Comment by MoAlyousef** [comment]
`app::GlobalState::<HashMap<String, String>>::new(HashMap::new());` doesn't cause an error on my system!

Regarding handling custom events in deactivated widgets, I think that depends on FLTK.

**Comment by theavege** [comment]
```
thread 'main' panicked at /home/tux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-1.4.32/src/app/state.rs:26:46:
called `Result::unwrap()` on an `Err` value: Mutex { data: Any { .. }, poisoned: false, .. }
```

**Comment by MoAlyousef** [comment]
I have no time for it

**Comment by theavege** [comment]
Unlock the repository. I've made the improvements I needed to the code.

**Comment by MoAlyousef** [comment]
This is a repo showcasing small bite-size demos. It's not a place to host personal projects, neither yours nor mine.  As such I'll be removing any sub-project which doesn't fit this from here. Please take the time to host them under your name, and continue developing them there. I don't need the continuous notifications about them.

**Comment by theavege** [comment]
Ok. It's all clear to me.
I've made improvements to flemish.
Can you accept them?
I've make a demo to help beginners.
I am ready to support Flemish.
Will you unlock the repository?

**Comment by MoAlyousef** [comment]
This also applies to flemish. I’m not sure why you seem against hosting projects under a seperate repo per project or under a repo with multiple demo projects (which I can point to as well), which I had suggested already several times before. You also said you wouldn’t add more demos to flemish. I’ve also stated several times before that I’m against copying or porting or people’s projects into here. You just seem to ignore everything and just do whatever you like. 
I don’t want to repeat every concern I have over and over.

**Comment by theavege** [comment]
You asked if I would maintain my edits. I will maintain and improve the code I edited.

**Comment by MoAlyousef** [comment]
https://github.com/fltk-rs/flemish/pull/10#issuecomment-2156017466

**Comment by theavege** [comment]
There is a condition that I support my code.

[And here is my attempt to get you interested in the project.](https://github.com/andersjoern/sudokusolver/issues/1)
[And here too.](https://github.com/andersjoern/b64converter/issues/1)

Don't You like that I add examples? Ok. Don't accept them. Roll back my all changes.
Accept only changes in lib.rs flemish.
That's all.
I'll leave your project. 
Flemish is a good project. 
I tried to improve it.

**Comment by MoAlyousef** [comment]
First of all, will do. Second of all, you don’t get to act entitled here. I don’t owe you anything. These are free open source projects. Make sure you understand this before trying to contribute to other projects as well.

**Pull request closed without merging**
