### PR TITLE
change from choice to inputchoice in fldialect nad add search function

### PR DESCRIPTION
**Pull request by theavege**

### CODE REVIEW

**Comment by theavege** [comment]
@MoAlyousef How can You add ```InputChoice.value_index() -> Some(i32)```? How to remove nesting in ```InputChoice.add("https://fltk-rs.github.io/fltk-book/")```?

**Comment by MoAlyousef** [comment]
I can try adding InputChoice::value_index() since FLTK doesn’t expose it. Regarding the nesting, you would have to escape the forward slashes with a backslash. The string has to be a string literal: `r#"http:\/\/site"`

**Comment by theavege** [comment]
@MoAlyousef , I can't understand the strange behavior in ```cairo_shadow_button```. Can You help me?

**Comment by MoAlyousef** [comment]
set_label cause a widget to redraw, i.e invoking the draw method again and again.

**Comment by theavege** [comment]
@MoAlyousef , sorry, I didn't understand. Why does ```window.set_label("")``` work, but ```frame.set_label("")``` don't work correct?

**Comment by theavege** [comment]
@MoAlyousef can you add a method ```frame.draw_label()``` without ```redraw()```?

**Comment by MoAlyousef** [comment]
Anything which causes a redraw like browser.clear() and frame.set_labe() if called inside the draw callback would cause issues.
How would frame.draw_label() be implemented, it would still require adding a draw::draw_text or something to the draw handler.

**Comment by theavege** [comment]
Thanks. I fixed the example with cairo's buttons. Why it don't work?

**Comment by theavege** [comment]
@MoAlyousef The [GlobalState](https://docs.rs/fltk/latest/fltk/app/struct.GlobalState.html) is very usefully. I remade demos cairo_button, csv and flpicture with ```GlobalState``` and ```widget.handle()```, but ```browser.handle()```  don't correct work in flpicture's demos. Need examples with MVC + GlobalState.

**Comment by MoAlyousef** [comment]
If you can create a minimal repro of the code not working it might help with finding out what issue it has. It could be a bug in FLTK.

**Comment by theavege** [comment]
@MoAlyousef I make [it](https://github.com/fltk-rs/fltk-rs/pull/1556).

**Comment by theavege** [comment]
@MoAlyousef Do you have any comments about MR? Will you accept?

**Comment by MoAlyousef** [comment]
The amount of changes is too large, and I'm busy these days. I'll review them when I have the time.

**Comment by MoAlyousef** [comment]
It seems flpicture wasn't updated and there's a bug when the browser is selected.
Also I'm not a fan of prefixing project/directory names with `fl`.
Also adding a model to each project will just add some burden to whoever reads the code. The code needs to be simple so already working code need not be modified for a new design pattern. For example, the cairo shadow button code is just to show how one can use cairo to create an FLTK widget. It's not meant to be a whole program with some architecture. 
I'm also not a fan of app::handle_main as the primary way of handling events. As such it should not be emphasized in the demos repo. And as you've seen, it can cause issues when the event isn't propagated correctly.

**Comment by theavege** [comment]
what architectural solution do you prefer?

**Comment by MoAlyousef** [comment]
Some new demos are ok. The demos which attempt to show interoperation with other libraries especially on how to integrate them with FLTK (like cairo for example), should show the minimal amount of code to get something working. It should be imperative, since it shouldn't assume how other devs using or integrating this code have structured their code.

**Comment by theavege** [comment]
I understood. But, what architectural solution do you prefer?

**Comment by theavege** [comment]
@MoAlyousef Please add handling for deactivated widgets.

**Comment by MoAlyousef** [comment]
Done

**Pull request merged**
