### PR TITLE
fix music

### PR DESCRIPTION
**Pull request by theavege**
@MoAlyousef  How to set false in menuItem (toggle)?

### CODE REVIEW

**Comment by theavege** [comment]
If you plan to improve [FLText](https://github.com/fltk-rs/demos/tree/master/fltext), then I advise you to follow the example of [Thonny](https://github.com/thonny/).

**Comment by theavege** [comment]
How can I set the minimum window size limits?

**Comment by MoAlyousef** [comment]
`MenuItem::set()` should toggle on/off depending on the current value. 
You can use `WindowExt::size_range(min_w, min_h, 0,0)`

**Comment by theavege** [comment]
Why doesn't this work? You need to resize the window to display it correctly.
```
use fltk::{enums::*, prelude::*, *};

fn main() {
    let app = app::App::default().with_scheme(app::AppScheme::Plastic);
    let mut win = window::Window::default().with_size(800, 600);
    let mut col = group::Flex::default_fill().column();
    let mut row = group::Flex::default();
    let mut button = button::Button::default().with_label("@+");
    frame::Frame::default();
    row.end();
    row.fixed(&button, 30);
    col.fixed(&row, 30);
    let mut tabs = group::Tabs::default_fill();
    {
        let page = group::Flex::default_fill()
            .with_label("    Main    ")
            .column();
        page.end();
    }
    tabs.end();
    tabs.auto_layout();
    col.end();
    col.set_margin(10);
    col.set_pad(10);
    win.end();
    win.make_resizable(true);
    win.show();
    button.set_callback({
        let mut tabs = tabs.clone();
        move |_| {
            let mut page = group::Flex::default_fill()
                .with_label(&format!("    Page {}    ", tabs.children()))
                .column();
            frame::Frame::default().with_label(&format!("{}", tabs.children()));
            page.end();
            page.set_trigger(CallbackTrigger::Closed);
            page.set_callback(move |page| {
                if app::callback_reason() == CallbackReason::Closed {
                    let mut parent = page.parent().unwrap();
                    parent.remove(page);
                    app::redraw();
                }
            });
            tabs.add(&page);
            app::redraw();
        }
    });
    app.run().unwrap();
}

```

**Comment by MoAlyousef** [comment]
```rust
button.set_callback({
        let mut tabs = tabs.clone();
        move |_| {
            let mut page = group::Flex::default_fill()
                .with_label(&format!("    Page {}    ", tabs.children()))
                .column();
            frame::Frame::default().with_label(&format!("{}", tabs.children()));
            page.end();
            page.set_trigger(CallbackTrigger::Closed);
            page.set_callback({
                let mut tabs = tabs.clone();
                move |page| {
                    if app::callback_reason() == CallbackReason::Closed {
                        tabs.remove(page);
                        app::redraw();
                    }
                }
            });
            tabs.add(&page);
            tabs.auto_layout();
        }
    });
```

**Comment by theavege** [comment]
> `MenuItem::set()` should toggle on/off depending on the current value. 
It don't work.

**Comment by theavege** [comment]
> You can use WindowExt::size_range(min_w, min_h, 0,0)
Great!!! Thank you!

**Comment by theavege** [comment]
> ```rust
> button.set_callback({
>         let mut tabs = tabs.clone();
>         move |_| {
>             let mut page = group::Flex::default_fill()
>                 .with_label(&format!("    Page {}    ", tabs.children()))
>                 .column();
>             frame::Frame::default().with_label(&format!("{}", tabs.children()));
>             page.end();
>             page.set_trigger(CallbackTrigger::Closed);
>             page.set_callback({
>                 let mut tabs = tabs.clone();
>                 move |page| {
>                     if app::callback_reason() == CallbackReason::Closed {
>                         tabs.remove(page);
>                         app::redraw();
>                     }
>                 }
>             });
>             tabs.add(&page);
>             tabs.auto_layout();
>         }
>     });
> ```

Thank you very much!!!

**Comment by MoAlyousef** [comment]
Can you try with `MenuItem::clear()`?

**Comment by theavege** [comment]
> Can you try with `MenuItem::clear()`?

it works! I think it's better to use the method ```.set(bool)```.

**Pull request merged**
