### PR TITLE
add callback

### PR DESCRIPTION
**Pull request by theavege**
@MoAlyousef, Terve!

* When to expect menuItem.do.callback()?
* I advise you  to mark the ```.emit()``` method deprecated, because It is better to use ```.set_callback()``` and ```.handle()``` with ```with_id()```, otherwise there will be problems in the application (for this reason I have rewritten FlDialect, FlCalculator, FlMusic and FlPicture.).
* I advise you  to mark the ```.column``` and ```.row()``` method deprecated for ```Flex```, because It is better to use ```.with_type(FlexType::Column)``` or ```.with_type(FlexType::Row)```.  Using the ```.with_type()``` method makes the code cleaner and the documentation simpler. I suggest doing the same for other objects.
* Why don't you use the [```cxx```](//cxx.rs) project to connect rust and fltk?

Kiitos.

### CODE REVIEW

**Comment by MoAlyousef** [comment]
Marhaban @theavege 

> When to expect menuItem.do.callback()?

By 21/4/2024

> I advise you to mark the .emit() method deprecated, because It is better to use .set_callback() and .handle() with with_id(), otherwise there will be problems in the application (for this reason I have rewritten FlDialect, FlCalculator, FlMusic and FlPicture.).

with_id() requires that fltk and fltk-rs are built in multithreaded support (default). 
emit() is also the basis for the flemish crate even though not absolutely necessary. I think it works well with the Rust model. 

> I advise you to mark the .column and .row() method deprecated for Flex, because It is better to use .with_type(FlexType::Column) or .with_type(FlexType::Row). Using the .with_type() method makes the code cleaner and the documentation simpler. I suggest doing the same for other objects.

These are convnience methods where I don’t see the harm in having them. Other gui toolkits also provide such methods. 

> Why don't you use the [cxx](https://cxx.rs/) project to connect rust and fltk?

I tried both cxx and autocxx. cxx required a lot of boilerplate which is neither C++ nor Rust. It’s some macro syntax which is difficult to debug. I wasn’t really pleased with it.  I tried to make it work at the time when it first appeared. 
Autocxx has issues with constructors for some reason among other issues. If autocxx works well I might use it instead. 
Having C bindings allows creating bindings in other languages as well.

**Comment by theavege** [comment]
Marhaban @MoAlyousef

Using ```.emit()``` and while ```app.wait()``` caused a noticeable slowdown compared to ```.set_callback()``` and ```handle()``` with ```.with_id()```.

**Comment by theavege** [comment]
Where is the release?

**Comment by MoAlyousef** [comment]
I mean when building with `cargo build —release` or `cargo run —release`

**Comment by theavege** [comment]
Where is the 1.4.29 release?

**Comment by MoAlyousef** [comment]
Sorry I got really busy last night. Hopefully by midnight this evening.

**Comment by theavege** [comment]
Thank you!

**Comment by theavege** [comment]
```
   Compiling flcalculator v0.0.1 (/home/tux/Desktop/demos/flcalculator)
error[E0061]: this method takes 1 argument but 0 arguments were supplied
   --> flcalculator/src/main.rs:130:10
    |
130 |     item.do_callback();
    |          ^^^^^^^^^^^-- an argument of type `&_` is missing
    |
note: method defined here
   --> /home/tux/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-1.4.29/src/menu.rs:645:12
    |
645 |     pub fn do_callback<W: MenuExt>(&mut self, w: &W) {
    |            ^^^^^^^^^^^
help: provide the argument
    |
130 |     item.do_callback(/* w */);
```

@MoAlyousef, What does it need? Why it's not [this](https://docs.rs/fltk/latest/fltk/prelude/trait.WidgetExt.html#tymethod.do_callback)?

**Comment by MoAlyousef** [comment]
Unlike Fl_Widget::do_callback(), The Fl_Menu_Item requires a widget for its do_callback method:
https://www.fltk.org/doc-1.4/structFl__Menu__Item.html#aac2832e9090da6efb3b00fc2435fa738

I’ll try to post an example soon.

**Pull request merged**
