### PR TITLE
add quit to fltext and bugfix in fldialect

### PR DESCRIPTION
**Pull request by theavege**
@MoAlyousef Links don't show in HelpDialog with default Scheme (for example FlDialect/Info).

### CODE REVIEW

**Comment by theavege** [comment]
@MoAlyousef I didn't change wgpu.

**Comment by theavege** [comment]
@MoAlyousef How to filter by choice? Can misc::InputChoice help me with this?

**Comment by MoAlyousef** [comment]
I'm not sure what you mean filter by choice, you can try InputChoice and see if it does so. 
I'll build the fldialect example and check the links issue.

**Comment by MoAlyousef** [comment]
It seems FLTK uses a contrast color between blue and background2 for Fl_Help_View links.
Adding `app::set_color(Color::Blue, 200, 200, 255);` under `ColorTheme::new(color_themes::DARK_THEME).apply();` would show the color. We set the FL_BLUE to a lighter blue color, so it contrasts with the dark theme basically.

**Pull request merged**
